name: wire
description: A implementation of the foundamentals type around the lightning network spec aka TLV format.
version: 0.0.1
homepage: https://github.com/dart-lightning/lndart.wire

environment:
  sdk: '>=2.15.1 <3.0.0'


# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
